# Generated by Django 3.2.3 on 2021-05-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personproperties',
            name='properties',
            field=models.JSONField(),
        ),
    ]
