# Generated by Django 3.2.3 on 2021-05-27 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20210527_1532'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonProperties',
            new_name='Person',
        ),
    ]
